# Generated by Django 5.0.7 on 2024-07-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding', models.BinaryField()),
                ('image', models.ImageField(upload_to='faces/')),
            ],
        ),
    ]
