# Generated by Django 5.0.7 on 2024-07-31 06:44

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faces/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FaceEmbedding',
        ),
    ]
